In [1]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import os
import time
import datetime
import copy

import xobjects as xo

from config import lhc_configs, particle_config_low, particle_config_mid, particle_config_high, run_config_quickest, run_config_quickest_no_chk, run_config_test, run_config_test_no_chk, run_config_dyn_indicator, run_config_ground_truth

import definitive_dyn_indicators.utils.xtrack_engine as xe

In [2]:
context = xo.ContextCupy()

particle_config = particle_config_low[0]
particle_config.samples = 100
lhc_config = lhc_configs[0]

run_config = run_config_test
run_config_nochk = run_config_test_no_chk


In [3]:
coso = xe.RunConfig(
    times = np.arange(100, 100100, 100),
    t_norm = 100,
    displacement_module = 1e-12,
    t_checkpoints = 100
)

In [4]:
intial_conditions = particle_config.get_initial_conditions()
displacement = particle_config.get_initial_conditions_with_displacement(
    run_config.displacement_module, "random")
displacement_x = particle_config.get_initial_conditions_with_displacement(
    run_config.displacement_module, "x")
displacement_px = particle_config.get_initial_conditions_with_displacement(
    run_config.displacement_module, "px")
displacement_y = particle_config.get_initial_conditions_with_displacement(
    run_config.displacement_module, "y")
displacement_py = particle_config.get_initial_conditions_with_displacement(
    run_config.displacement_module, "py")
displacement_zeta = particle_config.get_initial_conditions_with_displacement(
    run_config.displacement_module, "z")
displacement_delta = particle_config.get_initial_conditions_with_displacement(
    run_config.displacement_module, "delta")


In [5]:
particles = intial_conditions.create_particles(context=context)
particles_d = displacement.create_particles(context=context)

In [6]:
chk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config,

    particles_list = [
        particles.to_dict(),
        particles_d.to_dict(),
    ]
)

chk_nochk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config_nochk,

    particles_list = [
        particles.to_dict(),
        particles_d.to_dict(),
    ]
)

In [8]:
output = "lyapunov.hdf5"
output_nochk = "lyapunov_nochk.hdf5"

In [9]:
# if output exists, remove it
if os.path.exists(output):
    os.remove(output)

if os.path.exists(output_nochk):
    os.remove(output_nochk)

In [10]:
while not chk.completed:
    chk = xe.track_lyapunov(chk, output, context)

generating ./0e9053c409e248639e39f02e5bf01782.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '0e9053c409e248639e39f02e5bf01782' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 0e9053c409e248639e39f02e5bf01782.c -o ./0e9053c409e248639e39f02e5bf01782.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./0e9053c409e248639e39f02e5bf01782.o -o ./0e9053c409e248639e39f02e5bf01782.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


  0%|          | 0/4 [00:00<?, ?it/s]

Event sample, at time 10. Current time 0.


 50%|█████     | 2/4 [00:01<00:01,  1.91it/s]


Event normalize, at time 10. Current time 10.
Event checkpoint, at time 10. Current time 10.
generating ./379bbb355776491f84aa454a3fd8b6b8.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '379bbb355776491f84aa454a3fd8b6b8' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 379bbb355776491f84aa454a3fd8b6b8.c -o ./379bbb355776491f84aa454a3fd8b6b8.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./379bbb355776491f84aa454a3fd8b6b8.o -o ./379bbb355776491f84aa454a3fd8b6b8.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


  0%|          | 0/4 [00:00<?, ?it/s]

Event sample, at time 10. Current time 10.
Event normalize, at time 10. Current time 10.
Event checkpoint, at time 10. Current time 10.
Event sample, at time 20. Current time 10.


100%|██████████| 4/4 [00:00<00:00,  5.30it/s]


In [11]:
while not chk_nochk.completed:
    chk_nochk = xe.track_lyapunov(chk_nochk, output_nochk, context)

generating ./61a83a8ce4bf43a2ae40388543f11019.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '61a83a8ce4bf43a2ae40388543f11019' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 61a83a8ce4bf43a2ae40388543f11019.c -o ./61a83a8ce4bf43a2ae40388543f11019.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./61a83a8ce4bf43a2ae40388543f11019.o -o ./61a83a8ce4bf43a2ae40388543f11019.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


  0%|          | 0/3 [00:00<?, ?it/s]

Event sample, at time 10. Current time 0.


 33%|███▎      | 1/3 [00:00<00:01,  1.05it/s]

Event normalize, at time 10. Current time 10.
Event sample, at time 20. Current time 10.


100%|██████████| 3/3 [00:01<00:00,  1.75it/s]


In [12]:
with h5py.File(output, "r") as file:
    d0 = file[f"lyapunov/{20}"][:]

with h5py.File(output_nochk, "r") as file:
    d1 = file[f"lyapunov/{20}"][:]

In [13]:
d0

array([0.39760364, 0.41865896, 0.39973638, 0.43656767, 0.42991236,
       0.51205706,        nan,        nan,        nan,        nan,
       0.36760754, 0.4369447 , 0.40519935, 0.24827689, 0.41612878,
       0.49231386,        nan,        nan,        nan,        nan,
       0.46352451, 0.45953884, 0.43197557, 0.48164212, 0.4976152 ,
              nan,        nan,        nan,        nan,        nan,
       0.41307261, 0.4809441 , 0.45907684, 0.44806348, 0.24427514,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [14]:
d1

array([0.39760364, 0.41865896, 0.39973638, 0.43656767, 0.42991236,
       0.51205706,        nan,        nan,        nan,        nan,
       0.36760754, 0.4369447 , 0.40519935, 0.24827689, 0.41612878,
       0.49231386,        nan,        nan,        nan,        nan,
       0.46352451, 0.45953884, 0.43197557, 0.48164212, 0.4976152 ,
              nan,        nan,        nan,        nan,        nan,
       0.41307261, 0.4809441 , 0.45907684, 0.44806348, 0.24427514,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [15]:
particles = intial_conditions.create_particles(context=context)
particles_x = displacement_x.create_particles(context=context)
particles_px = displacement_px.create_particles(context=context)
particles_y = displacement_y.create_particles(context=context)
particles_py = displacement_py.create_particles(context=context)
particles_z = displacement_zeta.create_particles(context=context)
particles_d = displacement_delta.create_particles(context=context)


In [16]:
chk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config,

    particles_list = [
        particles.to_dict(),
        particles_x.to_dict(),
        particles_px.to_dict(),
        particles_y.to_dict(),
        particles_py.to_dict(),
        particles_z.to_dict(),
        particles_d.to_dict()
    ]
)

chk_nochk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config_nochk,

    particles_list=[
        particles.to_dict(),
        particles_x.to_dict(),
        particles_px.to_dict(),
        particles_y.to_dict(),
        particles_py.to_dict(),
        particles_z.to_dict(),
        particles_d.to_dict()
    ]
)


In [17]:
output = "ofli_lyapunov.hdf5"
output_nochk = "ofli_lyapunov_nochk.hdf5"

In [18]:
# if output exists, remove it
if os.path.exists(output):
    os.remove(output)

if os.path.exists(output_nochk):
    os.remove(output_nochk)

In [19]:
while not chk.completed:
    chk = xe.track_ortho_lyapunov(chk, output, context)

generating ./4a45c536c2554469b46ad76e7668a802.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '4a45c536c2554469b46ad76e7668a802' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 4a45c536c2554469b46ad76e7668a802.c -o ./4a45c536c2554469b46ad76e7668a802.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./4a45c536c2554469b46ad76e7668a802.o -o ./4a45c536c2554469b46ad76e7668a802.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


 50%|█████     | 2/4 [00:02<00:02,  1.45s/it]


generating ./d7711d08b45449eea7a3896e9cd738ae.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building 'd7711d08b45449eea7a3896e9cd738ae' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c d7711d08b45449eea7a3896e9cd738ae.c -o ./d7711d08b45449eea7a3896e9cd738ae.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./d7711d08b45449eea7a3896e9cd738ae.o -o ./d7711d08b45449eea7a3896e9cd738ae.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 4/4 [00:02<00:00,  1.66it/s]


In [20]:
while not chk_nochk.completed:
    chk_nochk = xe.track_ortho_lyapunov(chk_nochk, output_nochk, context)


generating ./f4a6258dc5274748abb283bc8e086beb.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building 'f4a6258dc5274748abb283bc8e086beb' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c f4a6258dc5274748abb283bc8e086beb.c -o ./f4a6258dc5274748abb283bc8e086beb.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./f4a6258dc5274748abb283bc8e086beb.o -o ./f4a6258dc5274748abb283bc8e086beb.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 3/3 [00:05<00:00,  1.67s/it]


In [21]:
with h5py.File(output, "r") as file:
    d0 = file[f"lyapunov/{20}"][:]

with h5py.File(output_nochk, "r") as file:
    d1 = file[f"lyapunov/{20}"][:]


In [22]:
d0

array([[ 0.12657575,  0.08668738,  0.08534254,  0.06865556, -0.0047325 ,
         0.39892632,         nan,         nan,         nan,         nan,
         0.08561305,  0.0866918 ,  0.08714773,  0.11941399,  0.07558157,
         0.23224121,         nan,         nan,         nan,         nan,
         0.08480291,  0.21299905,  0.08478922,  0.09261236,  0.13590643,
                nan,         nan,         nan,         nan,         nan,
         0.16132914,  0.08008226,  0.07731466,  0.12920488,  0.20854882,
                nan,         nan,         nan,         nan,         nan,
         0.12792045,  0.12297476,  0.04546679,  0.0622045 ,  0.30090453,
                nan,         nan,         nan,         nan,         nan,
         0.07881321,  0.08541754,  0.04506236,  0.02365202,  0.21653126,
                nan,         nan,         nan,         nan,         nan,
         0.24374883,  0.34166668,  0.25724447,  0.52310204,         nan,
                nan,         nan,         nan,     

In [23]:
d1

array([[ 0.12657575,  0.08668738,  0.08534254,  0.06865556, -0.0047325 ,
         0.39892632,         nan,         nan,         nan,         nan,
         0.08561305,  0.0866918 ,  0.08714773,  0.11941399,  0.07558157,
         0.23224121,         nan,         nan,         nan,         nan,
         0.08480291,  0.21299905,  0.08478922,  0.09261236,  0.13590643,
                nan,         nan,         nan,         nan,         nan,
         0.16132914,  0.08008226,  0.07731466,  0.12920488,  0.20854882,
                nan,         nan,         nan,         nan,         nan,
         0.12792045,  0.12297476,  0.04546679,  0.0622045 ,  0.30090453,
                nan,         nan,         nan,         nan,         nan,
         0.07881321,  0.08541754,  0.04506236,  0.02365202,  0.21653126,
                nan,         nan,         nan,         nan,         nan,
         0.24374883,  0.34166668,  0.25724447,  0.52310204,         nan,
                nan,         nan,         nan,     

In [24]:
particles = intial_conditions.create_particles(context=context)


In [25]:
chk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config,

    particles_list = [
        particles.to_dict()
    ]
)

chk_nochk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config_nochk,

    particles_list=[
        particles.to_dict()
    ]
)


In [26]:
output = "rem.hdf5"
output_nochk = "rem_nochk.hdf5"

In [27]:
# if output exists, remove it
if os.path.exists(output):
    os.remove(output)

if os.path.exists(output_nochk):
    os.remove(output_nochk)

In [28]:
while not chk.completed:
    chk = xe.track_reverse(chk, output, context)

generating ./16f47b9cf3b840ae8bc50eeeb4a8d6ec.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '16f47b9cf3b840ae8bc50eeeb4a8d6ec' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 16f47b9cf3b840ae8bc50eeeb4a8d6ec.c -o ./16f47b9cf3b840ae8bc50eeeb4a8d6ec.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./16f47b9cf3b840ae8bc50eeeb4a8d6ec.o -o ./16f47b9cf3b840ae8bc50eeeb4a8d6ec.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


 33%|███▎      | 1/3 [00:00<00:01,  1.35it/s]


generating ./34908fe6e6bc4d20913ce4eb8d067c96.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '34908fe6e6bc4d20913ce4eb8d067c96' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 34908fe6e6bc4d20913ce4eb8d067c96.c -o ./34908fe6e6bc4d20913ce4eb8d067c96.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./34908fe6e6bc4d20913ce4eb8d067c96.o -o ./34908fe6e6bc4d20913ce4eb8d067c96.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 3/3 [00:01<00:00,  2.84it/s]


In [29]:
while not chk_nochk.completed:
    chk_nochk = xe.track_reverse(chk_nochk, output_nochk, context)


generating ./be9ddd3490e04ea8ae8f65f351817f02.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building 'be9ddd3490e04ea8ae8f65f351817f02' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c be9ddd3490e04ea8ae8f65f351817f02.c -o ./be9ddd3490e04ea8ae8f65f351817f02.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./be9ddd3490e04ea8ae8f65f351817f02.o -o ./be9ddd3490e04ea8ae8f65f351817f02.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 2/2 [00:01<00:00,  1.11it/s]


In [30]:
with h5py.File(output, "r") as file:
    d0 = file[f"reverse/{20}"][:]

with h5py.File(output_nochk, "r") as file:
    d1 = file[f"reverse/{20}"][:]


In [31]:
d0

array([4.23915857e-15, 3.16970112e-15, 4.01050542e-15, 2.03560210e-15,
       2.21681822e-15, 9.02113025e-15,            nan,            nan,
                  nan,            nan, 4.09946505e-15, 4.07936323e-15,
       5.38914807e-15, 2.61656243e-15, 5.93631919e-15, 3.44922912e-15,
                  nan,            nan,            nan,            nan,
       3.23804170e-15, 1.14203091e-15, 8.11263951e-15, 4.78308818e-15,
       6.77779858e-15,            nan,            nan,            nan,
                  nan,            nan, 4.42550190e-15, 8.95034769e-15,
       9.71309201e-15, 7.33069728e-15, 1.49131771e-14,            nan,
                  nan,            nan,            nan,            nan,
       7.97727719e-15, 6.07757689e-15, 7.41186363e-15, 2.14717231e-15,
       2.46109480e-14,            nan,            nan,            nan,
                  nan,            nan, 7.47367343e-15, 1.09541789e-14,
       4.27417592e-15, 5.89385702e-12, 2.39884206e-14,            nan,
      

In [32]:
d1

array([4.23915857e-15, 3.16970112e-15, 4.01050542e-15, 2.03560210e-15,
       2.21681822e-15, 9.02113025e-15,            nan,            nan,
                  nan,            nan, 4.09946505e-15, 4.07936323e-15,
       5.38914807e-15, 2.61656243e-15, 5.93631919e-15, 3.44922912e-15,
                  nan,            nan,            nan,            nan,
       3.23804170e-15, 1.14203091e-15, 8.11263951e-15, 4.78308818e-15,
       6.77779858e-15,            nan,            nan,            nan,
                  nan,            nan, 4.42550190e-15, 8.95034769e-15,
       9.71309201e-15, 7.33069728e-15, 1.49131771e-14,            nan,
                  nan,            nan,            nan,            nan,
       7.97727719e-15, 6.07757689e-15, 7.41186363e-15, 2.14717231e-15,
       2.46109480e-14,            nan,            nan,            nan,
                  nan,            nan, 7.47367343e-15, 1.09541789e-14,
       4.27417592e-15, 5.89385702e-12, 2.39884206e-14,            nan,
      

In [33]:
particles = intial_conditions.create_particles(context=context)
particles_x = displacement_x.create_particles(context=context)
particles_y = displacement_y.create_particles(context=context)


In [34]:
chk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config,

    particles_list = [
        particles.to_dict(),
        particles_x.to_dict(),
        particles_y.to_dict(),
    ]
)

chk_nochk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config_nochk,

    particles_list=[
        particles.to_dict(),
        particles_x.to_dict(),
        particles_y.to_dict(),
    ]
)


In [35]:
output = "sali.hdf5"
output_nochk = "sali_nochk.hdf5"

In [36]:
# if output exists, remove it
if os.path.exists(output):
    os.remove(output)

if os.path.exists(output_nochk):
    os.remove(output_nochk)

In [37]:
while not chk.completed:
    chk = xe.track_sali(chk, output, context)

generating ./4a2c8ceec6664e7ebef5dd75813e20c2.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '4a2c8ceec6664e7ebef5dd75813e20c2' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 4a2c8ceec6664e7ebef5dd75813e20c2.c -o ./4a2c8ceec6664e7ebef5dd75813e20c2.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./4a2c8ceec6664e7ebef5dd75813e20c2.o -o ./4a2c8ceec6664e7ebef5dd75813e20c2.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


 50%|█████     | 2/4 [00:01<00:01,  1.57it/s]


generating ./55853c42acc04bd0b5ca79de4b630b11.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '55853c42acc04bd0b5ca79de4b630b11' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 55853c42acc04bd0b5ca79de4b630b11.c -o ./55853c42acc04bd0b5ca79de4b630b11.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./55853c42acc04bd0b5ca79de4b630b11.o -o ./55853c42acc04bd0b5ca79de4b630b11.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 4/4 [00:01<00:00,  3.96it/s]


In [38]:
while not chk_nochk.completed:
    chk_nochk = xe.track_sali(chk_nochk, output_nochk, context)


generating ./1c375aab9ebc4c2f8600143bc751c32c.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '1c375aab9ebc4c2f8600143bc751c32c' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 1c375aab9ebc4c2f8600143bc751c32c.c -o ./1c375aab9ebc4c2f8600143bc751c32c.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./1c375aab9ebc4c2f8600143bc751c32c.o -o ./1c375aab9ebc4c2f8600143bc751c32c.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 3/3 [00:02<00:00,  1.39it/s]


In [39]:
with h5py.File(output, "r") as file:
    d0 = file[f"sali/{20}"][:]

with h5py.File(output_nochk, "r") as file:
    d1 = file[f"sali/{20}"][:]


In [40]:
d0

array([0.29331355, 1.39718972, 1.40380148, 1.37555624, 1.32158718,
       0.19277663,        nan,        nan,        nan,        nan,
       1.40049046, 1.36775998, 1.35014068, 0.32068767, 1.08633083,
       1.24557504,        nan,        nan,        nan,        nan,
       1.40638219, 1.39281484, 1.2518883 , 1.15638448, 1.2159181 ,
              nan,        nan,        nan,        nan,        nan,
       0.1344216 , 1.29362541, 1.00230807, 0.24154999, 1.207007  ,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [41]:
d1

array([0.29331355, 1.39718972, 1.40380148, 1.37555624, 1.32158718,
       0.19277663,        nan,        nan,        nan,        nan,
       1.40049046, 1.36775998, 1.35014068, 0.32068767, 1.08633083,
       1.24557504,        nan,        nan,        nan,        nan,
       1.40638219, 1.39281484, 1.2518883 , 1.15638448, 1.2159181 ,
              nan,        nan,        nan,        nan,        nan,
       0.1344216 , 1.29362541, 1.00230807, 0.24154999, 1.207007  ,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [7]:
particles = intial_conditions.create_particles(context=context)
particles_x = displacement_x.create_particles(context=context)
particles_px = displacement_px.create_particles(context=context)
particles_y = displacement_y.create_particles(context=context)
particles_py = displacement_py.create_particles(context=context)


In [8]:
chk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config,

    particles_list = [
        particles.to_dict(),
        particles_x.to_dict(),
        particles_px.to_dict(),
        particles_y.to_dict(),
        particles_py.to_dict(),
    ]
)

chk_nochk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config_nochk,

    particles_list=[
        particles.to_dict(),
        particles_x.to_dict(),
        particles_px.to_dict(),
        particles_y.to_dict(),
        particles_py.to_dict(),
    ]
)


In [9]:
output = "gali4.hdf5"
output_nochk = "gali4_nochk.hdf5"

In [10]:
# if output exists, remove it
if os.path.exists(output):
    os.remove(output)

if os.path.exists(output_nochk):
    os.remove(output_nochk)

In [11]:
while not chk.completed:
    chk = xe.track_gali_4(chk, output, context)

generating ./699d77a5926b463f8b6b7b34f1410322.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '699d77a5926b463f8b6b7b34f1410322' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 699d77a5926b463f8b6b7b34f1410322.c -o ./699d77a5926b463f8b6b7b34f1410322.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./699d77a5926b463f8b6b7b34f1410322.o -o ./699d77a5926b463f8b6b7b34f1410322.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


 50%|█████     | 2/4 [00:02<00:02,  1.05s/it]


generating ./612da4e4fd614f07b6c26f7eba0aea8c.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '612da4e4fd614f07b6c26f7eba0aea8c' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 612da4e4fd614f07b6c26f7eba0aea8c.c -o ./612da4e4fd614f07b6c26f7eba0aea8c.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./612da4e4fd614f07b6c26f7eba0aea8c.o -o ./612da4e4fd614f07b6c26f7eba0aea8c.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 4/4 [00:01<00:00,  2.63it/s]


In [12]:
while not chk_nochk.completed:
    chk_nochk = xe.track_gali_4(chk_nochk, output_nochk, context)


generating ./3f0c88732fa14a7896676206ae4aa950.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '3f0c88732fa14a7896676206ae4aa950' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 3f0c88732fa14a7896676206ae4aa950.c -o ./3f0c88732fa14a7896676206ae4aa950.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./3f0c88732fa14a7896676206ae4aa950.o -o ./3f0c88732fa14a7896676206ae4aa950.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 3/3 [00:03<00:00,  1.19s/it]


In [13]:
with h5py.File(output, "r") as file:
    d0 = file[f"gali/{20}"][:]

with h5py.File(output_nochk, "r") as file:
    d1 = file[f"gali/{20}"][:]


In [14]:
d0

array([3.84467742e-05, 4.98220692e-05, 3.83668646e-06, 4.24936131e-05,
       1.54854373e-04, 8.53725122e-09,            nan,            nan,
                  nan,            nan, 1.07866264e-06, 9.78126098e-04,
       1.33304394e-05, 7.69254723e-05, 1.09798117e-03, 5.30519293e-06,
                  nan,            nan,            nan,            nan,
       1.06586447e-04, 2.05710361e-03, 6.77735262e-05, 8.08913084e-06,
       6.78154423e-05,            nan,            nan,            nan,
                  nan,            nan, 3.00482547e-05, 1.62623559e-04,
       1.01736439e-03, 2.37339822e-05, 9.89648639e-07,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
      

In [15]:
d1

array([3.84467742e-05, 4.98220692e-05, 3.83668646e-06, 4.24936131e-05,
       1.54854373e-04, 8.53725122e-09,            nan,            nan,
                  nan,            nan, 1.07866264e-06, 9.78126098e-04,
       1.33304394e-05, 7.69254723e-05, 1.09798117e-03, 5.30519293e-06,
                  nan,            nan,            nan,            nan,
       1.06586447e-04, 2.05710361e-03, 6.77735262e-05, 8.08913084e-06,
       6.78154423e-05,            nan,            nan,            nan,
                  nan,            nan, 3.00482547e-05, 1.62623559e-04,
       1.01736439e-03, 2.37339822e-05, 9.89648639e-07,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
      

In [16]:
particles = intial_conditions.create_particles(context=context)
particles_x = displacement_x.create_particles(context=context)
particles_px = displacement_px.create_particles(context=context)
particles_y = displacement_y.create_particles(context=context)
particles_py = displacement_py.create_particles(context=context)
particles_z = displacement_zeta.create_particles(context=context)
particles_d = displacement_delta.create_particles(context=context)


In [17]:
chk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config,

    particles_list = [
        particles.to_dict(),
        particles_x.to_dict(),
        particles_px.to_dict(),
        particles_y.to_dict(),
        particles_py.to_dict(),
        particles_z.to_dict(),
        particles_d.to_dict()
    ]
)

chk_nochk = xe.Checkpoint(
    particles_config=particle_config,
    lhc_config=lhc_config,
    run_config=run_config_nochk,

    particles_list=[
        particles.to_dict(),
        particles_x.to_dict(),
        particles_px.to_dict(),
        particles_y.to_dict(),
        particles_py.to_dict(),
        particles_z.to_dict(),
        particles_d.to_dict()
    ]
)


In [18]:
output = "gali.hdf5"
output_nochk = "gali_nochk.hdf5"

In [19]:
# if output exists, remove it
if os.path.exists(output):
    os.remove(output)

if os.path.exists(output_nochk):
    os.remove(output_nochk)

In [20]:
while not chk.completed:
    chk = xe.track_gali_6(chk, output, context)

generating ./2e20dd1026f249f29f1034f5709e3b80.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '2e20dd1026f249f29f1034f5709e3b80' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 2e20dd1026f249f29f1034f5709e3b80.c -o ./2e20dd1026f249f29f1034f5709e3b80.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./2e20dd1026f249f29f1034f5709e3b80.o -o ./2e20dd1026f249f29f1034f5709e3b80.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


 50%|█████     | 2/4 [00:03<00:03,  1.58s/it]


generating ./5cc5adcf7244475a9c87a7c8c5c54969.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building '5cc5adcf7244475a9c87a7c8c5c54969' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c 5cc5adcf7244475a9c87a7c8c5c54969.c -o ./5cc5adcf7244475a9c87a7c8c5c54969.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./5cc5adcf7244475a9c87a7c8c5c54969.o -o ./5cc5adcf7244475a9c87a7c8c5c54969.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 4/4 [00:02<00:00,  1.92it/s]


In [21]:
while not chk_nochk.completed:
    chk_nochk = xe.track_gali_6(chk_nochk, output_nochk, context)


generating ./d489ec17c7fd45f6b7038d886b01d79c.c
the current directory is '/home/camontan/Insync/carlo.montanari3@studio.unibo.it/OneDrive_Biz/projects/definitive_dyn_indicators/jobs/IPAC_LHC'
running build_ext
building 'd489ec17c7fd45f6b7038d886b01d79c' extension
gcc -pthread -B /home/camontan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/camontan/anaconda3/include/python3.8 -c d489ec17c7fd45f6b7038d886b01d79c.c -o ./d489ec17c7fd45f6b7038d886b01d79c.o -std=c99 -O3 -Wno-unused-function -fopenmp
gcc -pthread -shared -B /home/camontan/anaconda3/compiler_compat -L/home/camontan/anaconda3/lib -Wl,-rpath=/home/camontan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./d489ec17c7fd45f6b7038d886b01d79c.o -o ./d489ec17c7fd45f6b7038d886b01d79c.cpython-38-x86_64-linux-gnu.so -std=c99 -O3 -fopenmp


100%|██████████| 3/3 [00:04<00:00,  1.59s/it]


In [25]:
with h5py.File(output, "r") as file:
    d0 = file[f"gali/{20}"][:]

with h5py.File(output_nochk, "r") as file:
    d1 = file[f"gali/{10}"][:]


In [26]:
d0

array([1.25228798e-11, 1.02206861e-11, 1.97666354e-13, 6.97007690e-12,
       3.82256152e-11, 2.04994244e-16,            nan,            nan,
                  nan,            nan, 2.82774119e-14, 7.03939408e-10,
       7.47239035e-12, 8.22095718e-12, 2.36845637e-10, 4.19628648e-14,
                  nan,            nan,            nan,            nan,
       1.04012995e-10, 3.57324291e-10, 5.87099808e-11, 1.89970446e-13,
       6.26766103e-13,            nan,            nan,            nan,
                  nan,            nan, 4.75426447e-12, 5.90821313e-09,
       3.09775060e-10, 2.11096685e-12, 1.91486530e-12,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
      

In [27]:
d1

array([1.45938661e-07, 1.38679437e-07, 1.54911878e-07, 2.44095672e-07,
       3.17420934e-07, 1.72531201e-11,            nan,            nan,
                  nan,            nan, 1.23945829e-07, 1.22661887e-07,
       1.36925463e-07, 1.11717452e-07, 7.71432679e-07, 1.08859036e-09,
                  nan,            nan,            nan,            nan,
       1.20318622e-07, 4.16298108e-08, 1.40401102e-07, 1.03123043e-07,
       6.75081579e-09,            nan,            nan,            nan,
                  nan,            nan, 1.61228300e-07, 1.67215587e-07,
       2.43146889e-07, 3.49030952e-07, 3.64963277e-08,            nan,
                  nan,            nan,            nan,            nan,
       3.58918933e-07, 4.41068461e-07, 1.67163335e-06, 9.31276135e-08,
       1.96552111e-10,            nan,            nan,            nan,
                  nan,            nan, 1.25303639e-07, 5.22906909e-08,
       3.15310025e-07, 1.10463581e-08, 2.06515376e-09,            nan,
      